import 'styles/globals.scss'
import React, { PropsWithChildren } from 'react'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({ children }: PropsWithChildren) => (
  <html lang='en'>{children}</html>
)
export default RootLayout
